name: epic_grind
description: A mobile fitness RPG
version: 1.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^0.13.5
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/.env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

